### ISSUE TITLE
When vue block order is template, script, style, auto insert import statement error

### ISSUE THREAD

**Issue by Alkaidcc** [Simon-He95/fast-create-variable#11]
When vue block order is `template`, `script`, `style`, `import {ref} from vue` statement will be inserted into `template` block instead of `script` block.

Context: Using Vue3 setup syntax and Javascript

Expected: check script block position and insert.

**Comment by Simon-He95** [comment]
Can you provide a code example?

**Comment by Alkaidcc** [comment]
Reproduction: https://github.com/Alkaidcc/fast-create-issue

**Comment by Alkaidcc** [comment]
```vue
<template>
  <div>
    <button type="button">count is {{ count }}</button>
  </div>
</template>

<script setup>
// some comment
const aaa = ref('https://www.zhihu.com')

</script>

```

**Comment by Simon-He95** [comment]
Please try the latest version to see if it can solve the problem

**Comment by Alkaidcc** [comment]
Nope, but [unplugin-auto-import](https://github.com/unplugin/unplugin-auto-import) generate `auto-imports.d.ts` can fix it.

**Comment by Simon-He95** [comment]
v0.81.0 has fixed，thanks for your issue
