### ISSUE TITLE
Win11 will open Media Player

### ISSUE THREAD

**Issue by zifengb** [Simon-He95/fast-create-variable#11]
- OS: Window 11 家庭中文版
- version: 21H2
- OS version: 22000.1817
- fast-create-variable version: v0.0.29

插件命令触发时，会打开 Media Player
### ![image](https://github.com/Simon-He95/fast-create-variable/assets/17843939/70f6259b-674c-47dd-85ed-8985be0d439f)

**Comment by Simon-He95** [comment]
vscode 可以再设置中keyboard shortcuts里自己修改快捷键的指令
![Uploading image.png…]()

**Comment by zifengb** [comment]
已测试过，并不是快捷键冲突的问题，看起来和插件唤起执行的命令有关系

**Comment by xiyaowong** [comment]
我也有这个问题。要不作者考虑下删除播放音频的操作，没必要加入这种“功能”吧:joy:，或者提供一个配置关闭也行。
https://github.com/Simon-He95/fast-create-variable/blob/0249f22372f0345f25c35530fab8184a148afea5/src/index.ts#L16

**Comment by Simon-He95** [comment]
可能是用的第三方声音库产生的问题，我发一个版本默认关闭声音，可以自己配置开启，升级到v0.0.30应该就好了

**Comment by xiyaowong** [comment]
感谢！
