### ISSUE TITLE
选中了一个单词，且只有不能生在function  

### ISSUE THREAD

**Issue by canyonwan** [Simon-He95/fast-create-variable#12]
<img width="775" alt="image" src="https://github.com/Simon-He95/fast-create-variable/assets/17877692/ede5703e-24a1-49d0-9d83-59306788857b">
选中了一个单词，且只有不能生在function

**Comment by Simon-He95** [comment]
Please provide the smallest demo that can be reproduced, which can be this separate .vue file

**Comment by Simon-He95** [comment]
I will temporarily close it and need to provide more evidence and reproduction demo
