### ISSUE TITLE
[Requirement suggestion]: In the setup syntax scenario, add variable export.

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#13]
In the setup syntax of the vue component, when we create a variable in the template and the implementation of this variable is automatically created by the plugin, can we automatically insert this variable into the return statement of the setup synchronously?

I hope you'll take this suggestion! 🌹 🌹

**Comment by Simon-He95** [comment]
Because I don't recommend using defineComponent anymore, using script setup directly would be more concise
