### ISSUE TITLE
add params when create a function

### ISSUE THREAD

**Issue by HenryTSZ** [Simon-He95/fast-create-variable#15]

**Comment by Simon-He95** [comment]
> _No description provided._

why need this，when we create function ，we will jump to function

**Comment by HenryTSZ** [comment]
> > _No description provided._
> 
> why need this，when we create function ，we will jump to function

For example, I write a function: 

```js
handleChange(value, type, data)
```

When I create it using cmd+g, only get

```js
const handleChange = () => {

}
```

so I have to write the params by myself

I hope get this:

```js
const handleChange = (value, type, data) => {

}
```

It would be even better if we could infer the type

bty

When our params are base values rather than variables

```js
handleChange('test', 'input', {})
```

we can handle them this way

```js
const handleChange = (param1, param2, param3) => {

}
```

I think this method should be a code snippet. The cursor defaults to param1, and pressing the tab will jump to param2, param3

**Comment by Simon-He95** [comment]
try to update the latest version，it should work

**Comment by HenryTSZ** [comment]
Do I have to select the variable or function that needs to be created?


https://github.com/user-attachments/assets/e6cc29ea-cba2-4e1a-b854-152b50648de5

**Comment by Simon-He95** [comment]
you should select wrapper function or cursor in end of function like abc（xx）🖱️

**Comment by HenryTSZ** [comment]
> you should select wrapper function or cursor in end of function like abc（xx）🖱️

It seems like there are still some issues

https://github.com/user-attachments/assets/e7c381e9-51f6-4e7e-81f8-b35a6f86e557

**Comment by Simon-He95** [comment]
in v0.0.96, it works~
