### ISSUE TITLE
perplexity about v0.1.4 

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#16]
In the v0.1.4 release notes it says that user code snippets are supported, but I see that the configuration in the readme doesn't say where this is configured, is it in package.json or vscode's settings.json file?But I'd like to be able to configure it in a global place instead of binding it to the project. 

Thanks you

**Comment by Simon-He95** [comment]
I'm very glad that you are following this project. This is the direction I've been researching and trying recently. I just updated the [README](https://github.com/Simon-He95/fast-create-variable#-snippet) about snippet. It is based on vscode and does not distinguish between projects. You can configure which languages ​​it will take effect in by yourself.

**Comment by jzsn2018** [comment]
> I'm very glad that you are following this project. This is the direction I've been researching and trying recently. I just updated the [README](https://github.com/Simon-He95/fast-create-variable#-snippet) about snippet. It is based on vscode and does not distinguish between projects. You can configure which languages ​​it will take effect in by yourself.

Thanks you reply , I will try it.
