### ISSUE TITLE
【需求建议】能否支持构建单个函数的 return 

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#3]
## 单个函数体中构建 return 

我们一般会在 单独的 ts 文件中定义一些 hook 文件，例如下面的代码示例：

```ts
export const useTableData = () => {
      const variable1 = ref(xxx);
      const variable2 = ref(xxx);
      const variable3 = ref(xxx);

    // 这时候我们一般需要手动导出这些变量中的全部或者某个，能否支持这种场景下的 return 语句的构建

   return {
     xxx,
   }
}
```

希望大佬可以考虑上面的需求建议，感谢大佬🙏🙏🙏

**Comment by Simon-He95** [comment]
Okay, I understand, I will consider it, maybe this feature will be available next week

**Comment by jzsn2018** [comment]
> Okay, I understand, I will consider it, maybe this feature will be available next week

Thanks your reply~ Is it possible to support batch return of these variables in this scenario? Otherwise, exporting them one by one is not as efficient as copying them with multiple cursors and exporting them again.

**Comment by Simon-He95** [comment]
v0.0.45 Already have this ability
