### ISSUE TITLE
当data或者computed为空时，生成错误

### ISSUE THREAD

**Issue by liweiook** [Simon-He95/fast-create-variable#3]
![image](https://github.com/Simon-He95/fast-create-variable/assets/42706756/b776cf71-f588-4ba4-b7c7-e86d1a7f99a2)

**Comment by Simon-He95** [comment]
try to update 0.0.11, it will be fixed

**Comment by Simon-He95** [comment]
I'll close this issue first. If there are still problems, you can open it again.
