### ISSUE TITLE
需求建议：模板中的表达式抽取变量

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#4]
感谢大佬采纳了我上个需求建议，我更新体验了，非常nice 👍 👍 👍 。

## 场景描述

在 vue 模板中，有时候需要将一个三元表达式或者 其他逻辑表达式抽成 变量。这种场景后续考虑支持吗？

例如：
```vue
<div  v-if="xxx ? true : false"></div>
```
```vue
<div :class="['xxx', 'xxx', 'xxx]"></div>
```
能否选中 `['xxx', 'xxx', 'xxx]`  或者 `xxx ? true : false`，然后激活插件，让用户提供 变量名，然后再选择 变量类型 ，然后再生成代码

还有如果选择生成函数的类型时，能否支持 用户输入变量名的时候，直接将用户输入作为选中内容的替换.
> 这里想的是如果选择函数的类型，我们在模板中定义带参数函数的调用也是很常见的

## 示例

1. 用户选中完内容，触发插件事件，插件弹出下拉框，让用户选择生成变量的类型
2. 再次弹出输入框，让用户输入变量名

```bash
请输入变量名：getBoxCls(item)
```
3. 用户输入完这个字符串 `getBoxCls(item)` 之后，模板中的原始内容就变成如下

```diff
-<div :class="['xxx', 'xxx', 'xxx]"></div>

+<div :class="getBoxCls(item)"></div>
```

**Comment by Simon-He95** [comment]
你指的是像重构代码一样的吗😳，将选中区域抽出来用一个变量替换再底部实现

**Comment by jzsn2018** [comment]
> 你指的是像重构代码一样的吗😳，将选中区域抽出来用一个变量替换再底部实现

是的，就是这个意思，vscode现有的重构不支持这种模板中的重构

**Comment by Simon-He95** [comment]
我觉得做这件事的意义不大，觉得他不会有很大的使用场景
