### ISSUE TITLE
【需求建议】: Vue 中 setup 中 变量的  defineExpose

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#6]
```ts
setup(){
  const aa = ref('')

  defineExpose({
    aa
  })
}
```
当处于 setup 上下文或者 `<script lang="ts" setup></script>` 的根上下文时，希望在使用插件时，可以自动将变量导出在  `defineExpose `对象中。 感谢大佬 🌷

**Comment by Simon-He95** [comment]
The latest version is already available
