### ISSUE TITLE
【需求建议】： 是否考虑支持 vue2.6 版本的包的导入

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#7]
在 vue2.6 以下的项目，我们通常从 `vue-demi` 或者 `@vue/componsition-api` 中导入 ref computed 等依赖，目前插件都是从 vue 中导出的。在 vue2.6.x 版本中的项目，每次导出完之后还需要再改一下。 是否后续考虑根据 项目根目录的 package.json 中的vue依赖的版本号 去动态调整导入的包名？

感谢大佬 🌹 🌹

**Comment by Simon-He95** [comment]
v0.0.51 should already support it
