### ISSUE TITLE
【需求建议】：导入的语句有两个小优化

### ISSUE THREAD

**Issue by jzsn2018** [Simon-He95/fast-create-variable#8]
1. 比如我们现在需要从 `vue-demi` 导入 ref。但是当前文件已经存在了 从 vue-demi 中导入 ref 的语句。但是插件目前还是会生成一条 vue-demi  导出 ref  的语句。

2. 插件生成的 语句现在都在 脚本的第一行，一般项目里面第一行是注释行，可以调整一下逻辑，每次新增的 import 语句插入当前 import语句的最后一行吗？

```ts
<script lange="ts">
import { ref } from vue-demi // 插件会把语句生成在这里
/**
*@file 这是一个文件头注释
*/
import { A } from 'xxx'
import { A } from 'xxx'
import { A } from 'xxx'
import { A } from 'xxx'
// 能否将语句生成在 import 语句最后一行 ？
</script>
```
感谢大佬 🌹 🌹

**Comment by Simon-He95** [comment]
v0.0.52 will fix
